-- Jogadores Copa do Mundo 2026 — 48 seleções, 26 jogadores cada (1.248 total)
-- Fonte: Wikipedia / FIFA (junho 2026)
-- Executa no Supabase SQL Editor

DELETE FROM players;

INSERT INTO players (name, team_id, position, shirt_number)
SELECT v.name, t.id, v.position, v.shirt_number::int
FROM (VALUES
  -- ============================================================
  -- GRUPO A: República Tcheca, México, África do Sul, Coreia do Sul
  -- ============================================================
  ('CZE','Matěj Kovář','Goleiro',1),
  ('CZE','David Zima','Defensor',2),
  ('CZE','Tomáš Holeš','Defensor',3),
  ('CZE','Robin Hranáč','Defensor',4),
  ('CZE','Vladimír Coufal','Defensor',5),
  ('CZE','Štěpán Chaloupek','Defensor',6),
  ('CZE','Ladislav Krejčí','Defensor',7),
  ('CZE','Vladimír Darida','Meio-campista',8),
  ('CZE','Adam Hložek','Atacante',9),
  ('CZE','Patrik Schick','Atacante',10),
  ('CZE','Jan Kuchta','Atacante',11),
  ('CZE','Lukáš Červ','Meio-campista',12),
  ('CZE','Mojmír Chytil','Atacante',13),
  ('CZE','David Jurásek','Defensor',14),
  ('CZE','Pavel Šulc','Atacante',15),
  ('CZE','Jindřích Staněk','Goleiro',16),
  ('CZE','Lukáš Provod','Meio-campista',17),
  ('CZE','Michal Sadílek','Meio-campista',18),
  ('CZE','Tomáš Chorý','Atacante',19),
  ('CZE','Jaroslav Zelený','Defensor',20),
  ('CZE','David Douděra','Defensor',21),
  ('CZE','Tomáš Souček','Meio-campista',22),
  ('CZE','Lukáš Horníček','Goleiro',23),
  ('CZE','Alexandr Sojka','Meio-campista',24),
  ('CZE','Hugo Sochůrek','Meio-campista',25),
  ('CZE','Denis Višinský','Atacante',26),

  ('MEX','Raúl Rangel','Goleiro',1),
  ('MEX','Jorge Sánchez','Defensor',2),
  ('MEX','César Montes','Defensor',3),
  ('MEX','Edson Álvarez','Defensor',4),
  ('MEX','Johan Vásquez','Defensor',5),
  ('MEX','Érik Lira','Meio-campista',6),
  ('MEX','Luis Romo','Meio-campista',7),
  ('MEX','Álvaro Fidalgo','Meio-campista',8),
  ('MEX','Raúl Jiménez','Atacante',9),
  ('MEX','Alexis Vega','Atacante',10),
  ('MEX','Santiago Giménez','Atacante',11),
  ('MEX','Carlos Acevedo','Goleiro',12),
  ('MEX','Guillermo Ochoa','Goleiro',13),
  ('MEX','Armando González','Atacante',14),
  ('MEX','Israel Reyes','Defensor',15),
  ('MEX','Julián Quiñones','Atacante',16),
  ('MEX','Orbelín Pineda','Meio-campista',17),
  ('MEX','Obed Vargas','Meio-campista',18),
  ('MEX','Gilberto Mora','Meio-campista',19),
  ('MEX','Mateo Chávez','Defensor',20),
  ('MEX','César Huerta','Atacante',21),
  ('MEX','Guillermo Martínez','Atacante',22),
  ('MEX','Jesús Gallardo','Defensor',23),
  ('MEX','Luis Chávez','Meio-campista',24),
  ('MEX','Roberto Alvarado','Atacante',25),
  ('MEX','Brian Gutiérrez','Meio-campista',26),

  ('RSA','Ronwen Williams','Goleiro',1),
  ('RSA','Thabang Matuludi','Defensor',2),
  ('RSA','Khulumani Ndamane','Defensor',3),
  ('RSA','Teboho Mokoena','Meio-campista',4),
  ('RSA','Thalente Mbatha','Meio-campista',5),
  ('RSA','Aubrey Modiba','Defensor',6),
  ('RSA','Oswin Appollis','Atacante',7),
  ('RSA','Tshepang Moremi','Atacante',8),
  ('RSA','Lyle Foster','Atacante',9),
  ('RSA','Relebohile Mofokeng','Atacante',10),
  ('RSA','Themba Zwane','Meio-campista',11),
  ('RSA','Thapelo Maseko','Atacante',12),
  ('RSA','Sphephelo Sithole','Meio-campista',13),
  ('RSA','Mbekezeli Mbokazi','Defensor',14),
  ('RSA','Iqraam Rayners','Atacante',15),
  ('RSA','Sipho Chaine','Goleiro',16),
  ('RSA','Evidence Makgopa','Atacante',17),
  ('RSA','Samukele Kabini','Defensor',18),
  ('RSA','Nkosinathi Sibisi','Defensor',19),
  ('RSA','Khuliso Mudau','Defensor',20),
  ('RSA','Ime Okon','Defensor',21),
  ('RSA','Ricardo Goss','Goleiro',22),
  ('RSA','Jayden Adams','Meio-campista',23),
  ('RSA','Olwethu Makhanya','Defensor',24),
  ('RSA','Kamogelo Sebelebele','Atacante',25),
  ('RSA','Bradley Cross','Defensor',26),

  ('KOR','Kim Seung-gyu','Goleiro',1),
  ('KOR','Lee Han-beom','Defensor',2),
  ('KOR','Lee Gi-hyuk','Meio-campista',3),
  ('KOR','Kim Min-jae','Defensor',4),
  ('KOR','Kim Tae-hyeon','Defensor',5),
  ('KOR','Hwang In-beom','Meio-campista',6),
  ('KOR','Son Heung-min','Atacante',7),
  ('KOR','Paik Seung-ho','Meio-campista',8),
  ('KOR','Cho Gue-sung','Atacante',9),
  ('KOR','Lee Jae-sung','Meio-campista',10),
  ('KOR','Hwang Hee-chan','Meio-campista',11),
  ('KOR','Song Bum-keun','Goleiro',12),
  ('KOR','Lee Tae-seok','Defensor',13),
  ('KOR','Cho Wi-je','Defensor',14),
  ('KOR','Kim Moon-hwan','Defensor',15),
  ('KOR','Park Jin-seob','Defensor',16),
  ('KOR','Bae Jun-ho','Meio-campista',17),
  ('KOR','Oh Hyeon-gyu','Atacante',18),
  ('KOR','Lee Kang-in','Meio-campista',19),
  ('KOR','Yang Hyun-jun','Meio-campista',20),
  ('KOR','Jo Hyeon-woo','Goleiro',21),
  ('KOR','Seol Young-woo','Defensor',22),
  ('KOR','Jens Castrop','Defensor',23),
  ('KOR','Kim Jin-gyu','Meio-campista',24),
  ('KOR','Eom Ji-sung','Meio-campista',25),
  ('KOR','Lee Dong-gyeong','Meio-campista',26),

  -- ============================================================
  -- GRUPO B: Bósnia-Herzegovina, Canadá, Catar, Suíça
  -- ============================================================
  ('BIH','Nikola Vasilj','Goleiro',1),
  ('BIH','Nihad Mujakić','Defensor',2),
  ('BIH','Dennis Hadžikadunić','Defensor',3),
  ('BIH','Tarik Muharemović','Defensor',4),
  ('BIH','Sead Kolašinac','Defensor',5),
  ('BIH','Benjamin Tahirović','Meio-campista',6),
  ('BIH','Amar Dedić','Defensor',7),
  ('BIH','Armin Gigović','Meio-campista',8),
  ('BIH','Samed Baždar','Atacante',9),
  ('BIH','Ermedin Demirović','Atacante',10),
  ('BIH','Edin Džeko','Atacante',11),
  ('BIH','Mladen Jurkas','Goleiro',12),
  ('BIH','Ivan Bašić','Meio-campista',13),
  ('BIH','Ivan Šunjić','Meio-campista',14),
  ('BIH','Amar Memić','Meio-campista',15),
  ('BIH','Amir Hadžiahmetović','Meio-campista',16),
  ('BIH','Dženis Burnić','Meio-campista',17),
  ('BIH','Nikola Katić','Defensor',18),
  ('BIH','Kerim Alajbegović','Atacante',19),
  ('BIH','Esmir Bajraktarević','Atacante',20),
  ('BIH','Stjepan Radeljić','Defensor',21),
  ('BIH','Martin Zlomislić','Goleiro',22),
  ('BIH','Haris Tabaković','Atacante',23),
  ('BIH','Arjan Malić','Defensor',24),
  ('BIH','Jovo Lukić','Atacante',25),
  ('BIH','Ermin Mahmić','Meio-campista',26),

  ('CAN','Dayne St. Clair','Goleiro',1),
  ('CAN','Alistair Johnston','Defensor',2),
  ('CAN','Alfie Jones','Defensor',3),
  ('CAN','Luc de Fougerolles','Defensor',4),
  ('CAN','Joel Waterman','Defensor',5),
  ('CAN','Mathieu Choinière','Meio-campista',6),
  ('CAN','Stephen Eustáquio','Meio-campista',7),
  ('CAN','Ismaël Koné','Meio-campista',8),
  ('CAN','Cyle Larin','Atacante',9),
  ('CAN','Jonathan David','Atacante',10),
  ('CAN','Liam Millar','Meio-campista',11),
  ('CAN','Tani Oluwaseyi','Atacante',12),
  ('CAN','Derek Cornelius','Defensor',13),
  ('CAN','Jacob Shaffelburg','Meio-campista',14),
  ('CAN','Moïse Bombito','Defensor',15),
  ('CAN','Maxime Crépeau','Goleiro',16),
  ('CAN','Tajon Buchanan','Atacante',17),
  ('CAN','Owen Goodman','Goleiro',18),
  ('CAN','Alphonso Davies','Defensor',19),
  ('CAN','Ali Ahmed','Atacante',20),
  ('CAN','Jonathan Osorio','Meio-campista',21),
  ('CAN','Richie Laryea','Defensor',22),
  ('CAN','Niko Sigur','Defensor',23),
  ('CAN','Promise David','Atacante',24),
  ('CAN','Nathan Saliba','Meio-campista',25),
  ('CAN','Jayden Nelson','Atacante',26),

  ('QAT','Mahmud Abunada','Goleiro',1),
  ('QAT','Pedro Miguel','Defensor',2),
  ('QAT','Lucas Mendes','Defensor',3),
  ('QAT','Issa Laye','Defensor',4),
  ('QAT','Jassem Gaber','Defensor',5),
  ('QAT','Abdulaziz Hatem','Meio-campista',6),
  ('QAT','Ahmed Alaaeldin','Atacante',7),
  ('QAT','Edmilson Junior','Atacante',8),
  ('QAT','Mohammed Muntari','Atacante',9),
  ('QAT','Hassan Al-Haydos','Atacante',10),
  ('QAT','Akram Afif','Atacante',11),
  ('QAT','Karim Boudiaf','Meio-campista',12),
  ('QAT','Ayoub Al-Oui','Defensor',13),
  ('QAT','Homam Ahmed','Defensor',14),
  ('QAT','Yusuf Abdurisag','Atacante',15),
  ('QAT','Boualem Khoukhi','Defensor',16),
  ('QAT','Ahmed Al-Ganehi','Meio-campista',17),
  ('QAT','Sultan Al-Brake','Defensor',18),
  ('QAT','Almoez Ali','Atacante',19),
  ('QAT','Ahmed Fathy','Meio-campista',20),
  ('QAT','Salah Zakaria','Goleiro',21),
  ('QAT','Meshaal Barsham','Goleiro',22),
  ('QAT','Assim Madibo','Meio-campista',23),
  ('QAT','Tahsin Jamshid','Atacante',24),
  ('QAT','Al-Hashmi Al-Hussain','Defensor',25),
  ('QAT','Mohamed Manai','Atacante',26),

  ('SUI','Gregor Kobel','Goleiro',1),
  ('SUI','Miro Muheim','Defensor',2),
  ('SUI','Silvan Widmer','Defensor',3),
  ('SUI','Nico Elvedi','Defensor',4),
  ('SUI','Manuel Akanji','Defensor',5),
  ('SUI','Denis Zakaria','Meio-campista',6),
  ('SUI','Breel Embolo','Atacante',7),
  ('SUI','Remo Freuler','Meio-campista',8),
  ('SUI','Johan Manzambi','Meio-campista',9),
  ('SUI','Granit Xhaka','Meio-campista',10),
  ('SUI','Dan Ndoye','Atacante',11),
  ('SUI','Yvon Mvogo','Goleiro',12),
  ('SUI','Ricardo Rodriguez','Defensor',13),
  ('SUI','Ardon Jashari','Meio-campista',14),
  ('SUI','Djibril Sow','Meio-campista',15),
  ('SUI','Christian Fassnacht','Atacante',16),
  ('SUI','Rubén Vargas','Atacante',17),
  ('SUI','Eray Cömert','Defensor',18),
  ('SUI','Noah Okafor','Atacante',19),
  ('SUI','Michel Aebischer','Meio-campista',20),
  ('SUI','Marvin Keller','Goleiro',21),
  ('SUI','Fabian Rieder','Meio-campista',22),
  ('SUI','Zeki Amdouni','Atacante',23),
  ('SUI','Aurèle Amenda','Defensor',24),
  ('SUI','Luca Jaquez','Defensor',25),
  ('SUI','Cedric Itten','Atacante',26),

  -- ============================================================
  -- GRUPO C: Brasil, Haiti, Marrocos, Escócia
  -- ============================================================
  ('BRA','Alisson','Goleiro',1),
  ('BRA','Éderson Silva','Meio-campista',2),
  ('BRA','Gabriel Magalhães','Defensor',3),
  ('BRA','Marquinhos','Defensor',4),
  ('BRA','Casemiro','Meio-campista',5),
  ('BRA','Alex Sandro','Defensor',6),
  ('BRA','Vinícius Júnior','Atacante',7),
  ('BRA','Bruno Guimarães','Meio-campista',8),
  ('BRA','Matheus Cunha','Atacante',9),
  ('BRA','Neymar','Atacante',10),
  ('BRA','Raphinha','Atacante',11),
  ('BRA','Weverton','Goleiro',12),
  ('BRA','Danilo Luiz','Defensor',13),
  ('BRA','Bremer','Defensor',14),
  ('BRA','Léo Pereira','Defensor',15),
  ('BRA','Douglas Santos','Defensor',16),
  ('BRA','Fabinho','Meio-campista',17),
  ('BRA','Danilo Santos','Meio-campista',18),
  ('BRA','Endrick','Atacante',19),
  ('BRA','Lucas Paquetá','Meio-campista',20),
  ('BRA','Luiz Henrique','Atacante',21),
  ('BRA','Gabriel Martinelli','Atacante',22),
  ('BRA','Ederson Moraes','Goleiro',23),
  ('BRA','Roger Ibáñez','Defensor',24),
  ('BRA','Igor Thiago','Atacante',25),
  ('BRA','Rayan','Atacante',26),

  ('HAI','Johny Placide','Goleiro',1),
  ('HAI','Carlens Arcus','Defensor',2),
  ('HAI','Keeto Thermoncy','Defensor',3),
  ('HAI','Ricardo Adé','Defensor',4),
  ('HAI','Hannes Delcroix','Defensor',5),
  ('HAI','Carl Sainté','Meio-campista',6),
  ('HAI','Derrick Etienne Jr.','Atacante',7),
  ('HAI','Martin Expérience','Defensor',8),
  ('HAI','Duckens Nazon','Atacante',9),
  ('HAI','Jean-Ricner Bellegarde','Meio-campista',10),
  ('HAI','Louicius Deedson','Atacante',11),
  ('HAI','Alexandre Pierre','Goleiro',12),
  ('HAI','Duke Lacroix','Defensor',13),
  ('HAI','Garven Metusala','Defensor',14),
  ('HAI','Ruben Providence','Atacante',15),
  ('HAI','Lenny Joseph','Atacante',16),
  ('HAI','Danley Jean Jacques','Meio-campista',17),
  ('HAI','Wilson Isidor','Atacante',18),
  ('HAI','Yassin Fortuné','Atacante',19),
  ('HAI','Frantzdy Pierrot','Atacante',20),
  ('HAI','Josué Casimir','Atacante',21),
  ('HAI','Jean-Kévin Duverne','Defensor',22),
  ('HAI','Josué Duverger','Goleiro',23),
  ('HAI','Wilguens Paugain','Defensor',24),
  ('HAI','Dominique Simon','Meio-campista',25),
  ('HAI','Woodensky Pierre','Meio-campista',26),

  ('MAR','Yassine Bounou','Goleiro',1),
  ('MAR','Achraf Hakimi','Defensor',2),
  ('MAR','Noussair Mazraoui','Defensor',3),
  ('MAR','Sofyan Amrabat','Meio-campista',4),
  ('MAR','Marwane Saâdane','Defensor',5),
  ('MAR','Ayyoub Bouaddi','Meio-campista',6),
  ('MAR','Chemsdine Talbi','Meio-campista',7),
  ('MAR','Azzedine Ounahi','Meio-campista',8),
  ('MAR','Soufiane Rahimi','Atacante',9),
  ('MAR','Brahim Díaz','Atacante',10),
  ('MAR','Ismael Saibari','Meio-campista',11),
  ('MAR','Munir Mohamedi','Goleiro',12),
  ('MAR','Zakaria El Ouahdi','Defensor',13),
  ('MAR','Issa Diop','Defensor',14),
  ('MAR','Samir El Mourabet','Meio-campista',15),
  ('MAR','Gessime Yassine','Meio-campista',16),
  ('MAR','Amine Sbaï','Atacante',17),
  ('MAR','Chadi Riad','Defensor',18),
  ('MAR','Youssef Belammari','Defensor',19),
  ('MAR','Ayoub El Kaabi','Atacante',20),
  ('MAR','Ayoube Amaimouni','Atacante',21),
  ('MAR','Ahmed Reda Tagnaouti','Goleiro',22),
  ('MAR','Bilal El Khannouss','Meio-campista',23),
  ('MAR','Neil El Aynaoui','Meio-campista',24),
  ('MAR','Redouane Halhal','Defensor',25),
  ('MAR','Anass Salah-Eddine','Defensor',26),

  ('SCO','Angus Gunn','Goleiro',1),
  ('SCO','Aaron Hickey','Defensor',2),
  ('SCO','Andy Robertson','Defensor',3),
  ('SCO','Scott McTominay','Meio-campista',4),
  ('SCO','Grant Hanley','Defensor',5),
  ('SCO','Kieran Tierney','Defensor',6),
  ('SCO','John McGinn','Meio-campista',7),
  ('SCO','Tyler Fletcher','Meio-campista',8),
  ('SCO','Lyndon Dykes','Atacante',9),
  ('SCO','Ché Adams','Atacante',10),
  ('SCO','Ryan Christie','Meio-campista',11),
  ('SCO','Liam Kelly','Goleiro',12),
  ('SCO','Jack Hendry','Defensor',13),
  ('SCO','Ross Stewart','Atacante',14),
  ('SCO','John Souttar','Defensor',15),
  ('SCO','Dominic Hyam','Defensor',16),
  ('SCO','Ben Gannon-Doak','Atacante',17),
  ('SCO','George Hirst','Atacante',18),
  ('SCO','Lewis Ferguson','Meio-campista',19),
  ('SCO','Lawrence Shankland','Atacante',20),
  ('SCO','Craig Gordon','Goleiro',21),
  ('SCO','Nathan Patterson','Defensor',22),
  ('SCO','Kenny McLean','Meio-campista',23),
  ('SCO','Anthony Ralston','Defensor',24),
  ('SCO','Findlay Curtis','Atacante',25),
  ('SCO','Scott McKenna','Defensor',26),

  -- ============================================================
  -- GRUPO D: Austrália, Paraguai, Turquia, EUA
  -- ============================================================
  ('AUS','Mathew Ryan','Goleiro',1),
  ('AUS','Miloš Degenek','Defensor',2),
  ('AUS','Alessandro Circati','Defensor',3),
  ('AUS','Jacob Italiano','Defensor',4),
  ('AUS','Jordan Bos','Defensor',5),
  ('AUS','Jason Geria','Defensor',6),
  ('AUS','Mathew Leckie','Atacante',7),
  ('AUS','Connor Metcalfe','Meio-campista',8),
  ('AUS','Mohamed Touré','Atacante',9),
  ('AUS','Ajdin Hrustic','Atacante',10),
  ('AUS','Awer Mabil','Atacante',11),
  ('AUS','Paul Izzo','Goleiro',12),
  ('AUS','Aiden O''Neill','Meio-campista',13),
  ('AUS','Cammy Devlin','Meio-campista',14),
  ('AUS','Kai Trewin','Defensor',15),
  ('AUS','Aziz Behich','Defensor',16),
  ('AUS','Nestory Irankunda','Atacante',17),
  ('AUS','Patrick Beach','Goleiro',18),
  ('AUS','Harry Souttar','Defensor',19),
  ('AUS','Cristian Volpato','Atacante',20),
  ('AUS','Cameron Burgess','Defensor',21),
  ('AUS','Jackson Irvine','Meio-campista',22),
  ('AUS','Nishan Velupillay','Atacante',23),
  ('AUS','Paul Okon-Engstler','Meio-campista',24),
  ('AUS','Lucas Herrington','Defensor',25),
  ('AUS','Tete Yengi','Atacante',26),

  ('PAR','Gatito Fernández','Goleiro',1),
  ('PAR','Gustavo Velázquez','Defensor',2),
  ('PAR','Omar Alderete','Defensor',3),
  ('PAR','Juan José Cáceres','Defensor',4),
  ('PAR','Fabián Balbuena','Defensor',5),
  ('PAR','Júnior Alonso','Defensor',6),
  ('PAR','Ramón Sosa','Meio-campista',7),
  ('PAR','Diego Gómez','Meio-campista',8),
  ('PAR','Antonio Sanabria','Atacante',9),
  ('PAR','Miguel Almirón','Meio-campista',10),
  ('PAR','Maurício','Meio-campista',11),
  ('PAR','Orlando Gill','Goleiro',12),
  ('PAR','José Canale','Defensor',13),
  ('PAR','Andrés Cubas','Meio-campista',14),
  ('PAR','Gustavo Gómez','Defensor',15),
  ('PAR','Damián Bobadilla','Meio-campista',16),
  ('PAR','Kaku','Atacante',17),
  ('PAR','Álex Arce','Atacante',18),
  ('PAR','Julio Enciso','Atacante',19),
  ('PAR','Braian Ojeda','Meio-campista',20),
  ('PAR','Gabriel Ávalos','Atacante',21),
  ('PAR','Gastón Olveira','Goleiro',22),
  ('PAR','Matías Galarza','Meio-campista',23),
  ('PAR','Gustavo Caballero','Meio-campista',24),
  ('PAR','Isidro Pitta','Atacante',25),
  ('PAR','Alexandro Maidana','Defensor',26),

  ('TUR','Mert Günok','Goleiro',1),
  ('TUR','Zeki Çelik','Defensor',2),
  ('TUR','Merih Demiral','Defensor',3),
  ('TUR','Çağlar Söyüncü','Defensor',4),
  ('TUR','Salih Özcan','Meio-campista',5),
  ('TUR','Orkun Kökçü','Meio-campista',6),
  ('TUR','Kerem Aktürkoğlu','Atacante',7),
  ('TUR','Arda Güler','Atacante',8),
  ('TUR','Deniz Gül','Atacante',9),
  ('TUR','Hakan Çalhanoğlu','Meio-campista',10),
  ('TUR','Kenan Yıldız','Atacante',11),
  ('TUR','Altay Bayındır','Goleiro',12),
  ('TUR','Eren Elmalı','Defensor',13),
  ('TUR','Abdülkerim Bardakçı','Defensor',14),
  ('TUR','Ozan Kabak','Defensor',15),
  ('TUR','İsmail Yüksek','Meio-campista',16),
  ('TUR','İrfan Can Kahveci','Atacante',17),
  ('TUR','Mert Müldür','Defensor',18),
  ('TUR','Yunus Akgün','Atacante',19),
  ('TUR','Ferdi Kadıoğlu','Defensor',20),
  ('TUR','Barış Alper Yılmaz','Atacante',21),
  ('TUR','Kaan Ayhan','Meio-campista',22),
  ('TUR','Uğurcan Çakır','Goleiro',23),
  ('TUR','Oğuz Aydın','Atacante',24),
  ('TUR','Samet Akaydin','Defensor',25),
  ('TUR','Can Uzun','Atacante',26),

  ('USA','Matt Turner','Goleiro',1),
  ('USA','Sergio Dest','Defensor',2),
  ('USA','Chris Richards','Defensor',3),
  ('USA','Tyler Adams','Meio-campista',4),
  ('USA','Antonee Robinson','Defensor',5),
  ('USA','Auston Trusty','Defensor',6),
  ('USA','Giovanni Reyna','Meio-campista',7),
  ('USA','Weston McKennie','Meio-campista',8),
  ('USA','Ricardo Pepi','Atacante',9),
  ('USA','Christian Pulisic','Atacante',10),
  ('USA','Brenden Aaronson','Atacante',11),
  ('USA','Miles Robinson','Defensor',12),
  ('USA','Tim Ream','Defensor',13),
  ('USA','Sebastian Berhalter','Meio-campista',14),
  ('USA','Cristian Roldan','Meio-campista',15),
  ('USA','Alex Freeman','Defensor',16),
  ('USA','Malik Tillman','Meio-campista',17),
  ('USA','Max Arfsten','Defensor',18),
  ('USA','Haji Wright','Atacante',19),
  ('USA','Folarin Balogun','Atacante',20),
  ('USA','Timothy Weah','Atacante',21),
  ('USA','Mark McKenzie','Defensor',22),
  ('USA','Joe Scally','Defensor',23),
  ('USA','Matt Freese','Goleiro',24),
  ('USA','Chris Brady','Goleiro',25),
  ('USA','Alejandro Zendejas','Atacante',26),

  -- ============================================================
  -- GRUPO E: Curaçao, Equador, Alemanha, Costa do Marfim
  -- ============================================================
  ('CUW','Eloy Room','Goleiro',1),
  ('CUW','Shurandy Sambo','Defensor',2),
  ('CUW','Jurién Gaari','Defensor',3),
  ('CUW','Roshon van Eijma','Defensor',4),
  ('CUW','Sherel Floranus','Defensor',5),
  ('CUW','Godfried Roemeratoe','Meio-campista',6),
  ('CUW','Juninho Bacuna','Meio-campista',7),
  ('CUW','Livano Comenencia','Meio-campista',8),
  ('CUW','Jürgen Locadia','Atacante',9),
  ('CUW','Leandro Bacuna','Meio-campista',10),
  ('CUW','Jeremy Antonisse','Atacante',11),
  ('CUW','Sontje Hansen','Atacante',12),
  ('CUW','Tyrese Noslin','Atacante',13),
  ('CUW','Kenji Gorré','Atacante',14),
  ('CUW','Ar''jany Martha','Meio-campista',15),
  ('CUW','Jearl Margaritha','Atacante',16),
  ('CUW','Brandley Kuwas','Atacante',17),
  ('CUW','Armando Obispo','Defensor',18),
  ('CUW','Gervane Kastaneer','Atacante',19),
  ('CUW','Joshua Brenet','Defensor',20),
  ('CUW','Tahith Chong','Meio-campista',21),
  ('CUW','Kevin Felida','Meio-campista',22),
  ('CUW','Riechedly Bazoer','Defensor',23),
  ('CUW','Deveron Fonville','Defensor',24),
  ('CUW','Tyrick Bodak','Goleiro',25),
  ('CUW','Trevor Doornbusch','Goleiro',26),

  ('ECU','Hernán Galíndez','Goleiro',1),
  ('ECU','Félix Torres','Defensor',2),
  ('ECU','Piero Hincapié','Defensor',3),
  ('ECU','Joel Ordóñez','Defensor',4),
  ('ECU','Jordy Alcívar','Meio-campista',5),
  ('ECU','Willian Pacho','Defensor',6),
  ('ECU','Pervis Estupiñán','Defensor',7),
  ('ECU','Anthony Valencia','Meio-campista',8),
  ('ECU','John Yeboah','Atacante',9),
  ('ECU','Kendry Páez','Meio-campista',10),
  ('ECU','Kevin Rodríguez','Atacante',11),
  ('ECU','Moisés Ramírez','Goleiro',12),
  ('ECU','Enner Valencia','Atacante',13),
  ('ECU','Alan Minda','Meio-campista',14),
  ('ECU','Pedro Vite','Meio-campista',15),
  ('ECU','Jordy Caicedo','Atacante',16),
  ('ECU','Ángelo Preciado','Defensor',17),
  ('ECU','Denil Castillo','Meio-campista',18),
  ('ECU','Gonzalo Plata','Atacante',19),
  ('ECU','Nilson Angulo','Atacante',20),
  ('ECU','Alan Franco','Meio-campista',21),
  ('ECU','Gonzalo Valle','Goleiro',22),
  ('ECU','Moisés Caicedo','Meio-campista',23),
  ('ECU','Jeremy Arévalo','Atacante',24),
  ('ECU','Jackson Porozo','Defensor',25),
  ('ECU','Yaimar Medina','Defensor',26),

  ('GER','Manuel Neuer','Goleiro',1),
  ('GER','Antonio Rüdiger','Defensor',2),
  ('GER','Waldemar Anton','Defensor',3),
  ('GER','Jonathan Tah','Defensor',4),
  ('GER','Aleksandar Pavlović','Meio-campista',5),
  ('GER','Joshua Kimmich','Meio-campista',6),
  ('GER','Kai Havertz','Atacante',7),
  ('GER','Leon Goretzka','Meio-campista',8),
  ('GER','Jamie Leweling','Meio-campista',9),
  ('GER','Jamal Musiala','Meio-campista',10),
  ('GER','Nick Woltemade','Atacante',11),
  ('GER','Oliver Baumann','Goleiro',12),
  ('GER','Pascal Groß','Meio-campista',13),
  ('GER','Maximilian Beier','Atacante',14),
  ('GER','Nico Schlotterbeck','Defensor',15),
  ('GER','Angelo Stiller','Meio-campista',16),
  ('GER','Florian Wirtz','Meio-campista',17),
  ('GER','Nathaniel Brown','Defensor',18),
  ('GER','Leroy Sané','Meio-campista',19),
  ('GER','Nadiem Amiri','Meio-campista',20),
  ('GER','Alexander Nübel','Goleiro',21),
  ('GER','David Raum','Defensor',22),
  ('GER','Felix Nmecha','Meio-campista',23),
  ('GER','Malick Thiaw','Defensor',24),
  ('GER','Assan Ouédraogo','Meio-campista',25),
  ('GER','Deniz Undav','Atacante',26),

  ('CIV','Yahia Fofana','Goleiro',1),
  ('CIV','Ousmane Diomande','Defensor',2),
  ('CIV','Ghislain Konan','Defensor',3),
  ('CIV','Jean Michaël Seri','Meio-campista',4),
  ('CIV','Wilfried Singo','Defensor',5),
  ('CIV','Seko Fofana','Meio-campista',6),
  ('CIV','Odilon Kossounou','Defensor',7),
  ('CIV','Franck Kessié','Meio-campista',8),
  ('CIV','Ange-Yoan Bonny','Atacante',9),
  ('CIV','Simon Adingra','Atacante',10),
  ('CIV','Yan Diomande','Atacante',11),
  ('CIV','Elye Wahi','Atacante',12),
  ('CIV','Christopher Opéri','Defensor',13),
  ('CIV','Oumar Diakité','Atacante',14),
  ('CIV','Amad Diallo','Atacante',15),
  ('CIV','Mohamed Koné','Goleiro',16),
  ('CIV','Guéla Doué','Defensor',17),
  ('CIV','Ibrahim Sangaré','Meio-campista',18),
  ('CIV','Nicolas Pépé','Atacante',19),
  ('CIV','Emmanuel Agbadou','Defensor',20),
  ('CIV','Evan Ndicka','Defensor',21),
  ('CIV','Evann Guessand','Atacante',22),
  ('CIV','Alban Lafont','Goleiro',23),
  ('CIV','Bazoumana Touré','Atacante',24),
  ('CIV','Parfait Guiagon','Meio-campista',25),
  ('CIV','Christ Inao Oulaï','Meio-campista',26),

  -- ============================================================
  -- GRUPO F: Japão, Holanda, Suécia, Tunísia
  -- ============================================================
  ('JPN','Zion Suzuki','Goleiro',1),
  ('JPN','Yukinari Sugawara','Defensor',2),
  ('JPN','Shōgo Taniguchi','Defensor',3),
  ('JPN','Kō Itakura','Defensor',4),
  ('JPN','Yūto Nagatomo','Defensor',5),
  ('JPN','Shūto Machino','Atacante',6),
  ('JPN','Ao Tanaka','Meio-campista',7),
  ('JPN','Takefusa Kubo','Meio-campista',8),
  ('JPN','Keisuke Gotō','Atacante',9),
  ('JPN','Ritsu Dōan','Meio-campista',10),
  ('JPN','Daizen Maeda','Meio-campista',11),
  ('JPN','Keisuke Ōsako','Goleiro',12),
  ('JPN','Keito Nakamura','Meio-campista',13),
  ('JPN','Junya Itō','Meio-campista',14),
  ('JPN','Daichi Kamada','Meio-campista',15),
  ('JPN','Tsuyoshi Watanabe','Defensor',16),
  ('JPN','Yuito Suzuki','Meio-campista',17),
  ('JPN','Ayase Ueda','Atacante',18),
  ('JPN','Kōki Ogawa','Atacante',19),
  ('JPN','Ayumu Seko','Defensor',20),
  ('JPN','Hiroki Itō','Defensor',21),
  ('JPN','Takehiro Tomiyasu','Defensor',22),
  ('JPN','Tomoki Hayakawa','Goleiro',23),
  ('JPN','Kaishu Sano','Meio-campista',24),
  ('JPN','Junnosuke Suzuki','Defensor',25),
  ('JPN','Kento Shiogai','Atacante',26),

  ('NED','Bart Verbruggen','Goleiro',1),
  ('NED','Lutsharel Geertruida','Defensor',2),
  ('NED','Marten de Roon','Meio-campista',3),
  ('NED','Virgil van Dijk','Defensor',4),
  ('NED','Nathan Aké','Defensor',5),
  ('NED','Jan Paul van Hecke','Defensor',6),
  ('NED','Justin Kluivert','Meio-campista',7),
  ('NED','Ryan Gravenberch','Meio-campista',8),
  ('NED','Wout Weghorst','Atacante',9),
  ('NED','Memphis Depay','Atacante',10),
  ('NED','Cody Gakpo','Atacante',11),
  ('NED','Mats Wieffer','Defensor',12),
  ('NED','Robin Roefs','Goleiro',13),
  ('NED','Tijjani Reijnders','Meio-campista',14),
  ('NED','Micky van de Ven','Defensor',15),
  ('NED','Guus Til','Meio-campista',16),
  ('NED','Noa Lang','Atacante',17),
  ('NED','Donyell Malen','Atacante',18),
  ('NED','Brian Brobbey','Atacante',19),
  ('NED','Teun Koopmeiners','Meio-campista',20),
  ('NED','Frenkie de Jong','Meio-campista',21),
  ('NED','Denzel Dumfries','Defensor',22),
  ('NED','Mark Flekken','Goleiro',23),
  ('NED','Crysencio Summerville','Atacante',24),
  ('NED','Jorrel Hato','Defensor',25),
  ('NED','Quinten Timber','Meio-campista',26),

  ('SWE','Jacob Widell Zetterström','Goleiro',1),
  ('SWE','Gustaf Lagerbielke','Defensor',2),
  ('SWE','Victor Lindelöf','Defensor',3),
  ('SWE','Isak Hien','Defensor',4),
  ('SWE','Gabriel Gudmundsson','Defensor',5),
  ('SWE','Herman Johansson','Defensor',6),
  ('SWE','Lucas Bergvall','Meio-campista',7),
  ('SWE','Daniel Svensson','Defensor',8),
  ('SWE','Alexander Isak','Atacante',9),
  ('SWE','Benjamin Nygren','Meio-campista',10),
  ('SWE','Anthony Elanga','Atacante',11),
  ('SWE','Viktor Johansson','Goleiro',12),
  ('SWE','Ken Sema','Meio-campista',13),
  ('SWE','Hjalmar Ekdal','Defensor',14),
  ('SWE','Carl Starfelt','Defensor',15),
  ('SWE','Jesper Karlström','Meio-campista',16),
  ('SWE','Viktor Gyökeres','Atacante',17),
  ('SWE','Yasin Ayari','Meio-campista',18),
  ('SWE','Mattias Svanberg','Meio-campista',19),
  ('SWE','Eric Smith','Defensor',20),
  ('SWE','Alexander Bernhardsson','Defensor',21),
  ('SWE','Besfort Zeneli','Meio-campista',22),
  ('SWE','Kristoffer Nordfeldt','Goleiro',23),
  ('SWE','Elliot Stroud','Defensor',24),
  ('SWE','Gustaf Nilsson','Atacante',25),
  ('SWE','Taha Ali','Atacante',26),

  ('TUN','Mouhib Chamakh','Goleiro',1),
  ('TUN','Ali Abdi','Defensor',2),
  ('TUN','Montassar Talbi','Defensor',3),
  ('TUN','Omar Rekik','Defensor',4),
  ('TUN','Adem Arous','Defensor',5),
  ('TUN','Dylan Bronn','Defensor',6),
  ('TUN','Elias Achouri','Atacante',7),
  ('TUN','Elias Saad','Atacante',8),
  ('TUN','Hazem Mastouri','Atacante',9),
  ('TUN','Hannibal Mejbri','Meio-campista',10),
  ('TUN','Ismaël Gharbi','Meio-campista',11),
  ('TUN','Mortadha Ben Ouanes','Defensor',12),
  ('TUN','Rani Khedira','Meio-campista',13),
  ('TUN','Khalil Ayari','Meio-campista',14),
  ('TUN','Hadj Mahmoud','Meio-campista',15),
  ('TUN','Aymen Dahmen','Goleiro',16),
  ('TUN','Ellyes Skhiri','Meio-campista',17),
  ('TUN','Rayan Elloumi','Atacante',18),
  ('TUN','Firas Chaouat','Atacante',19),
  ('TUN','Yan Valery','Defensor',20),
  ('TUN','Mohamed Amine Ben Hamida','Defensor',21),
  ('TUN','Sabri Ben Hessen','Goleiro',22),
  ('TUN','Moutaz Neffati','Defensor',23),
  ('TUN','Raed Chikhaoui','Defensor',24),
  ('TUN','Anis Ben Slimane','Meio-campista',25),
  ('TUN','Sebastian Tounekti','Meio-campista',26),

  -- ============================================================
  -- GRUPO G: Bélgica, Egito, Irã, Nova Zelândia
  -- ============================================================
  ('BEL','Thibaut Courtois','Goleiro',1),
  ('BEL','Zeno Debast','Defensor',2),
  ('BEL','Arthur Theate','Defensor',3),
  ('BEL','Brandon Mechele','Defensor',4),
  ('BEL','Maxim De Cuyper','Defensor',5),
  ('BEL','Axel Witsel','Meio-campista',6),
  ('BEL','Kevin De Bruyne','Meio-campista',7),
  ('BEL','Youri Tielemans','Meio-campista',8),
  ('BEL','Romelu Lukaku','Atacante',9),
  ('BEL','Leandro Trossard','Atacante',10),
  ('BEL','Jérémy Doku','Atacante',11),
  ('BEL','Senne Lammens','Goleiro',12),
  ('BEL','Mike Penders','Goleiro',13),
  ('BEL','Dodi Lukébakio','Atacante',14),
  ('BEL','Thomas Meunier','Defensor',15),
  ('BEL','Koni De Winter','Defensor',16),
  ('BEL','Charles De Ketelaere','Atacante',17),
  ('BEL','Joaquin Seys','Defensor',18),
  ('BEL','Diego Moreira','Meio-campista',19),
  ('BEL','Hans Vanaken','Meio-campista',20),
  ('BEL','Timothy Castagne','Defensor',21),
  ('BEL','Alexis Saelemaekers','Meio-campista',22),
  ('BEL','Nicolas Raskin','Meio-campista',23),
  ('BEL','Amadou Onana','Meio-campista',24),
  ('BEL','Nathan Ngoy','Defensor',25),
  ('BEL','Matias Fernandez-Pardo','Atacante',26),

  ('EGY','Mohamed El Shenawy','Goleiro',1),
  ('EGY','Yasser Ibrahim','Defensor',2),
  ('EGY','Mohamed Hany','Defensor',3),
  ('EGY','Hossam Abdelmaguid','Defensor',4),
  ('EGY','Ramy Rabia','Defensor',5),
  ('EGY','Mohamed Abdelmonem','Defensor',6),
  ('EGY','Trézéguet','Atacante',7),
  ('EGY','Emam Ashour','Meio-campista',8),
  ('EGY','Hamza Abdelkarim','Atacante',9),
  ('EGY','Mohamed Salah','Atacante',10),
  ('EGY','Mostafa Ziko','Meio-campista',11),
  ('EGY','Haissem Hassan','Atacante',12),
  ('EGY','Ahmed Fatouh','Defensor',13),
  ('EGY','Hamdy Fathy','Meio-campista',14),
  ('EGY','Karim Hafez','Defensor',15),
  ('EGY','El Mahdy Soliman','Goleiro',16),
  ('EGY','Mohanad Lasheen','Meio-campista',17),
  ('EGY','Nabil Emad','Meio-campista',18),
  ('EGY','Marwan Attia','Meio-campista',19),
  ('EGY','Ibrahim Adel','Atacante',20),
  ('EGY','Mahmoud Saber','Meio-campista',21),
  ('EGY','Omar Marmoush','Atacante',22),
  ('EGY','Mostafa Shobeir','Goleiro',23),
  ('EGY','Tarek Alaa','Defensor',24),
  ('EGY','Zizo','Atacante',25),
  ('EGY','Mohamed Alaa','Goleiro',26),

  ('IRN','Alireza Beiranvand','Goleiro',1),
  ('IRN','Saleh Hardani','Defensor',2),
  ('IRN','Ehsan Hajsafi','Defensor',3),
  ('IRN','Shojae Khalilzadeh','Defensor',4),
  ('IRN','Milad Mohammadi','Defensor',5),
  ('IRN','Saeid Ezatolahi','Meio-campista',6),
  ('IRN','Alireza Jahanbakhsh','Meio-campista',7),
  ('IRN','Mohammad Mohebi','Meio-campista',8),
  ('IRN','Mehdi Taremi','Atacante',9),
  ('IRN','Mehdi Ghayedi','Atacante',10),
  ('IRN','Ali Alipour','Atacante',11),
  ('IRN','Payam Niazmand','Goleiro',12),
  ('IRN','Hossein Kanaanizadegan','Defensor',13),
  ('IRN','Saman Ghoddos','Meio-campista',14),
  ('IRN','Rouzbeh Cheshmi','Meio-campista',15),
  ('IRN','Mahdi Torabi','Meio-campista',16),
  ('IRN','Arya Yousefi','Defensor',17),
  ('IRN','Amirhossein Hosseinzadeh','Atacante',18),
  ('IRN','Ali Nemati','Defensor',19),
  ('IRN','Shahriyar Moghanlou','Atacante',20),
  ('IRN','Mohammad Ghorbani','Meio-campista',21),
  ('IRN','Hossein Hosseini','Goleiro',22),
  ('IRN','Ramin Rezaeian','Defensor',23),
  ('IRN','Dennis Eckert','Atacante',24),
  ('IRN','Danial Eiri','Defensor',25),
  ('IRN','Amirmohammad Razzaghinia','Meio-campista',26),

  ('NZL','Max Crocombe','Goleiro',1),
  ('NZL','Tim Payne','Defensor',2),
  ('NZL','Francis de Vries','Defensor',3),
  ('NZL','Tyler Bindon','Defensor',4),
  ('NZL','Michael Boxall','Defensor',5),
  ('NZL','Joe Bell','Meio-campista',6),
  ('NZL','Logan Rogerson','Atacante',7),
  ('NZL','Marko Stamenić','Meio-campista',8),
  ('NZL','Chris Wood','Atacante',9),
  ('NZL','Sarpreet Singh','Meio-campista',10),
  ('NZL','Elijah Just','Meio-campista',11),
  ('NZL','Alex Paulsen','Goleiro',12),
  ('NZL','Liberato Cacace','Defensor',13),
  ('NZL','Alex Rufer','Meio-campista',14),
  ('NZL','Nando Pijnaker','Defensor',15),
  ('NZL','Finn Surman','Defensor',16),
  ('NZL','Kosta Barbarouses','Atacante',17),
  ('NZL','Ben Waine','Atacante',18),
  ('NZL','Ben Old','Meio-campista',19),
  ('NZL','Callum McCowatt','Meio-campista',20),
  ('NZL','Jesse Randall','Atacante',21),
  ('NZL','Michael Woud','Goleiro',22),
  ('NZL','Ryan Thomas','Meio-campista',23),
  ('NZL','Callan Elliot','Defensor',24),
  ('NZL','Lachlan Bayliss','Meio-campista',25),
  ('NZL','Tommy Smith','Defensor',26),

  -- ============================================================
  -- GRUPO H: Cabo Verde, Arábia Saudita, Espanha, Uruguai
  -- ============================================================
  ('CPV','Vozinha','Goleiro',1),
  ('CPV','Stopira','Defensor',2),
  ('CPV','Diney','Defensor',3),
  ('CPV','Pico Lopes','Defensor',4),
  ('CPV','Logan Costa','Defensor',5),
  ('CPV','Kevin Pina','Meio-campista',6),
  ('CPV','Jovane Cabral','Meio-campista',7),
  ('CPV','João Paulo Fernandes','Meio-campista',8),
  ('CPV','Gilson Benchimol','Atacante',9),
  ('CPV','Jamiro Monteiro','Meio-campista',10),
  ('CPV','Garry Rodrigues','Meio-campista',11),
  ('CPV','Mário Rosa','Goleiro',12),
  ('CPV','Sidny Lopes Cabral','Defensor',13),
  ('CPV','Deroy Duarte','Meio-campista',14),
  ('CPV','Laros Duarte','Meio-campista',15),
  ('CPV','Yannick Semedo','Meio-campista',16),
  ('CPV','Willy Semedo','Meio-campista',17),
  ('CPV','Telmo Arcanjo','Meio-campista',18),
  ('CPV','Dailon Livramento','Atacante',19),
  ('CPV','Ryan Mendes','Atacante',20),
  ('CPV','Nuno da Costa','Meio-campista',21),
  ('CPV','Steven Moreira','Defensor',22),
  ('CPV','CJ dos Santos','Goleiro',23),
  ('CPV','Wagner Pina','Defensor',24),
  ('CPV','Kelvin Pires','Defensor',25),
  ('CPV','Hélio Varela','Meio-campista',26),

  ('SAU','Nawaf Al-Aqidi','Goleiro',1),
  ('SAU','Ali Majrashi','Defensor',2),
  ('SAU','Ali Lajami','Defensor',3),
  ('SAU','Abdulelah Al-Amri','Defensor',4),
  ('SAU','Hassan Al-Tambakti','Defensor',5),
  ('SAU','Nasser Al-Dawsari','Meio-campista',6),
  ('SAU','Musab Al-Juwayr','Meio-campista',7),
  ('SAU','Ayman Yahya','Atacante',8),
  ('SAU','Firas Al-Buraikan','Atacante',9),
  ('SAU','Salem Al-Dawsari','Atacante',10),
  ('SAU','Saleh Al-Shehri','Atacante',11),
  ('SAU','Saud Abdulhamid','Defensor',12),
  ('SAU','Nawaf Boushal','Defensor',13),
  ('SAU','Hassan Kadesh','Defensor',14),
  ('SAU','Abdullah Al-Khaibari','Meio-campista',15),
  ('SAU','Ziyad Al-Johani','Meio-campista',16),
  ('SAU','Khalid Al-Ghannam','Atacante',17),
  ('SAU','Alaa Al-Hejji','Meio-campista',18),
  ('SAU','Abdullah Al-Hamdan','Atacante',19),
  ('SAU','Sultan Mandash','Atacante',20),
  ('SAU','Mohammed Al-Owais','Goleiro',21),
  ('SAU','Ahmed Al-Kassar','Goleiro',22),
  ('SAU','Mohamed Kanno','Meio-campista',23),
  ('SAU','Moteb Al-Harbi','Defensor',24),
  ('SAU','Jehad Thakri','Defensor',25),
  ('SAU','Mohammed Abu Al-Shamat','Defensor',26),

  ('ESP','David Raya','Goleiro',1),
  ('ESP','Marc Pubill','Defensor',2),
  ('ESP','Álex Grimaldo','Defensor',3),
  ('ESP','Eric García','Defensor',4),
  ('ESP','Marcos Llorente','Defensor',5),
  ('ESP','Mikel Merino','Meio-campista',6),
  ('ESP','Ferran Torres','Atacante',7),
  ('ESP','Fabián Ruiz','Meio-campista',8),
  ('ESP','Gavi','Meio-campista',9),
  ('ESP','Dani Olmo','Atacante',10),
  ('ESP','Yéremy Pino','Atacante',11),
  ('ESP','Pedro Porro','Defensor',12),
  ('ESP','Joan Garcia','Goleiro',13),
  ('ESP','Aymeric Laporte','Defensor',14),
  ('ESP','Álex Baena','Meio-campista',15),
  ('ESP','Rodri','Meio-campista',16),
  ('ESP','Nico Williams','Atacante',17),
  ('ESP','Martín Zubimendi','Meio-campista',18),
  ('ESP','Lamine Yamal','Atacante',19),
  ('ESP','Pedri','Meio-campista',20),
  ('ESP','Mikel Oyarzabal','Atacante',21),
  ('ESP','Pau Cubarsí','Defensor',22),
  ('ESP','Unai Simón','Goleiro',23),
  ('ESP','Marc Cucurella','Defensor',24),
  ('ESP','Víctor Muñoz','Atacante',25),
  ('ESP','Borja Iglesias','Atacante',26),

  ('URU','Sergio Rochet','Goleiro',1),
  ('URU','José María Giménez','Defensor',2),
  ('URU','Sebastián Cáceres','Defensor',3),
  ('URU','Ronald Araújo','Defensor',4),
  ('URU','Manuel Ugarte','Meio-campista',5),
  ('URU','Rodrigo Bentancur','Meio-campista',6),
  ('URU','Nicolás de la Cruz','Meio-campista',7),
  ('URU','Federico Valverde','Meio-campista',8),
  ('URU','Darwin Núñez','Atacante',9),
  ('URU','Giorgian de Arrascaeta','Meio-campista',10),
  ('URU','Facundo Pellistri','Atacante',11),
  ('URU','Santiago Mele','Goleiro',12),
  ('URU','Guillermo Varela','Defensor',13),
  ('URU','Agustín Canobbio','Meio-campista',14),
  ('URU','Emiliano Martínez','Meio-campista',15),
  ('URU','Mathías Olivera','Defensor',16),
  ('URU','Matías Viña','Defensor',17),
  ('URU','Brian Rodríguez','Atacante',18),
  ('URU','Rodrigo Aguirre','Atacante',19),
  ('URU','Maximiliano Araújo','Meio-campista',20),
  ('URU','Federico Viñas','Atacante',21),
  ('URU','Joaquín Piquerez','Meio-campista',22),
  ('URU','Fernando Muslera','Goleiro',23),
  ('URU','Santiago Bueno','Defensor',24),
  ('URU','Juan Manuel Sanabria','Meio-campista',25),
  ('URU','Rodrigo Zalazar','Meio-campista',26),

  -- ============================================================
  -- GRUPO I: França, Iraque, Noruega, Senegal
  -- ============================================================
  ('FRA','Brice Samba','Goleiro',1),
  ('FRA','Malo Gusto','Defensor',2),
  ('FRA','Lucas Digne','Defensor',3),
  ('FRA','Dayot Upamecano','Defensor',4),
  ('FRA','Jules Koundé','Defensor',5),
  ('FRA','Manu Koné','Meio-campista',6),
  ('FRA','Ousmane Dembélé','Atacante',7),
  ('FRA','Aurélien Tchouaméni','Meio-campista',8),
  ('FRA','Marcus Thuram','Atacante',9),
  ('FRA','Kylian Mbappé','Atacante',10),
  ('FRA','Michael Olise','Atacante',11),
  ('FRA','Bradley Barcola','Atacante',12),
  ('FRA','N''Golo Kanté','Meio-campista',13),
  ('FRA','Adrien Rabiot','Meio-campista',14),
  ('FRA','Ibrahima Konate','Defensor',15),
  ('FRA','Mike Maignan','Goleiro',16),
  ('FRA','William Saliba','Defensor',17),
  ('FRA','Warren Zaïre-Emery','Meio-campista',18),
  ('FRA','Théo Hernandez','Defensor',19),
  ('FRA','Désiré Doué','Atacante',20),
  ('FRA','Lucas Hernandez','Defensor',21),
  ('FRA','Jean-Philippe Mateta','Atacante',22),
  ('FRA','Robin Risser','Goleiro',23),
  ('FRA','Rayan Cherki','Meio-campista',24),
  ('FRA','Maghnes Akliouche','Meio-campista',25),
  ('FRA','Maxence Lacroix','Defensor',26),

  ('IRQ','Fahad Talib','Goleiro',1),
  ('IRQ','Rebin Sulaka','Defensor',2),
  ('IRQ','Hussein Ali','Defensor',3),
  ('IRQ','Zaid Tahseen','Defensor',4),
  ('IRQ','Akam Hashim','Defensor',5),
  ('IRQ','Manaf Younis','Defensor',6),
  ('IRQ','Youssef Amyn','Meio-campista',7),
  ('IRQ','Ibrahim Bayesh','Meio-campista',8),
  ('IRQ','Ali Al-Hamadi','Atacante',9),
  ('IRQ','Mohanad Ali','Atacante',10),
  ('IRQ','Ahmed Qasem','Atacante',11),
  ('IRQ','Jalal Hassan','Goleiro',12),
  ('IRQ','Ali Yousif','Atacante',13),
  ('IRQ','Zidane Iqbal','Meio-campista',14),
  ('IRQ','Ahmed Maknzi','Defensor',15),
  ('IRQ','Amir Al-Ammari','Meio-campista',16),
  ('IRQ','Ali Jasim','Atacante',17),
  ('IRQ','Aymen Hussein','Atacante',18),
  ('IRQ','Kevin Yakob','Meio-campista',19),
  ('IRQ','Aimar Sher','Meio-campista',20),
  ('IRQ','Marko Farji','Atacante',21),
  ('IRQ','Ahmed Basil','Goleiro',22),
  ('IRQ','Merchas Doski','Defensor',23),
  ('IRQ','Zaid Ismail','Meio-campista',24),
  ('IRQ','Mustafa Saadoon','Defensor',25),
  ('IRQ','Frans Putros','Defensor',26),

  ('NOR','Ørjan Nyland','Goleiro',1),
  ('NOR','Morten Thorsby','Meio-campista',2),
  ('NOR','Kristoffer Ajer','Defensor',3),
  ('NOR','Leo Østigård','Defensor',4),
  ('NOR','David Møller Wolfe','Defensor',5),
  ('NOR','Patrick Berg','Meio-campista',6),
  ('NOR','Alexander Sørloth','Atacante',7),
  ('NOR','Sander Berge','Meio-campista',8),
  ('NOR','Erling Haaland','Atacante',9),
  ('NOR','Martin Ødegaard','Meio-campista',10),
  ('NOR','Jørgen Strand Larsen','Atacante',11),
  ('NOR','Sander Tangvik','Goleiro',12),
  ('NOR','Egil Selvik','Goleiro',13),
  ('NOR','Fredrik Aursnes','Meio-campista',14),
  ('NOR','Fredrik André Bjørkan','Defensor',15),
  ('NOR','Marcus Holmgren Pedersen','Defensor',16),
  ('NOR','Torbjørn Heggem','Defensor',17),
  ('NOR','Kristian Thorstvedt','Meio-campista',18),
  ('NOR','Thelo Aasgaard','Meio-campista',19),
  ('NOR','Antonio Nusa','Meio-campista',20),
  ('NOR','Andreas Schjelderup','Meio-campista',21),
  ('NOR','Oscar Bobb','Meio-campista',22),
  ('NOR','Jens Petter Hauge','Meio-campista',23),
  ('NOR','Sondre Langås','Defensor',24),
  ('NOR','Henrik Falchener','Defensor',25),
  ('NOR','Julian Ryerson','Defensor',26),

  ('SEN','Yehvann Diouf','Goleiro',1),
  ('SEN','Mamadou Sarr','Defensor',2),
  ('SEN','Kalidou Koulibaly','Defensor',3),
  ('SEN','Abdoulaye Seck','Defensor',4),
  ('SEN','Idrissa Gueye','Meio-campista',5),
  ('SEN','Pathé Ciss','Meio-campista',6),
  ('SEN','Assane Diao','Atacante',7),
  ('SEN','Lamine Camara','Meio-campista',8),
  ('SEN','Bamba Dieng','Atacante',9),
  ('SEN','Sadio Mané','Atacante',10),
  ('SEN','Nicolas Jackson','Atacante',11),
  ('SEN','Cherif Ndiaye','Atacante',12),
  ('SEN','Iliman Ndiaye','Atacante',13),
  ('SEN','Ismail Jakobs','Defensor',14),
  ('SEN','Krépin Diatta','Defensor',15),
  ('SEN','Édouard Mendy','Goleiro',16),
  ('SEN','Pape Matar Sarr','Meio-campista',17),
  ('SEN','Ismaïla Sarr','Atacante',18),
  ('SEN','Moussa Niakhaté','Defensor',19),
  ('SEN','Ibrahim Mbaye','Atacante',20),
  ('SEN','Habib Diarra','Meio-campista',21),
  ('SEN','Bara Sapoko Ndiaye','Meio-campista',22),
  ('SEN','Mory Diaw','Goleiro',23),
  ('SEN','Antoine Mendy','Defensor',24),
  ('SEN','El Hadji Malick Diouf','Defensor',25),
  ('SEN','Pape Gueye','Meio-campista',26),

  -- ============================================================
  -- GRUPO J: Argélia, Argentina, Áustria, Jordânia
  -- ============================================================
  ('ALG','Melvin Mastil','Goleiro',1),
  ('ALG','Aïssa Mandi','Defensor',2),
  ('ALG','Achref Abada','Defensor',3),
  ('ALG','Mohamed Amine Tougai','Defensor',4),
  ('ALG','Zineddine Belaïd','Defensor',5),
  ('ALG','Ramiz Zerrouki','Meio-campista',6),
  ('ALG','Riyad Mahrez','Atacante',7),
  ('ALG','Houssem Aouar','Meio-campista',8),
  ('ALG','Amine Gouiri','Atacante',9),
  ('ALG','Farès Chaïbi','Meio-campista',10),
  ('ALG','Anis Hadj Moussa','Atacante',11),
  ('ALG','Nadhir Benbouali','Atacante',12),
  ('ALG','Jaouen Hadjam','Defensor',13),
  ('ALG','Hicham Boudaoui','Meio-campista',14),
  ('ALG','Rayan Aït-Nouri','Defensor',15),
  ('ALG','Oussama Benbot','Goleiro',16),
  ('ALG','Rafik Belghali','Defensor',17),
  ('ALG','Mohamed Amoura','Atacante',18),
  ('ALG','Nabil Bentaleb','Meio-campista',19),
  ('ALG','Adil Boulbina','Atacante',20),
  ('ALG','Ramy Bensebaini','Defensor',21),
  ('ALG','Ibrahim Maza','Meio-campista',22),
  ('ALG','Luca Zidane','Goleiro',23),
  ('ALG','Yacine Titraoui','Meio-campista',24),
  ('ALG','Farès Ghedjemis','Atacante',25),
  ('ALG','Samir Chergui','Defensor',26),

  ('ARG','Juan Musso','Goleiro',1),
  ('ARG','Marcos Senesi','Defensor',2),
  ('ARG','Nicolás Tagliafico','Defensor',3),
  ('ARG','Gonzalo Montiel','Defensor',4),
  ('ARG','Leandro Paredes','Meio-campista',5),
  ('ARG','Lisandro Martínez','Defensor',6),
  ('ARG','Rodrigo De Paul','Meio-campista',7),
  ('ARG','Valentín Barco','Meio-campista',8),
  ('ARG','Julián Alvarez','Atacante',9),
  ('ARG','Lionel Messi','Atacante',10),
  ('ARG','Giovani Lo Celso','Meio-campista',11),
  ('ARG','Gerónimo Rulli','Goleiro',12),
  ('ARG','Cristian Romero','Defensor',13),
  ('ARG','Exequiel Palacios','Meio-campista',14),
  ('ARG','Nicolás González','Meio-campista',15),
  ('ARG','Thiago Almada','Atacante',16),
  ('ARG','Giuliano Simeone','Atacante',17),
  ('ARG','Nico Paz','Atacante',18),
  ('ARG','Nicolás Otamendi','Defensor',19),
  ('ARG','Alexis Mac Allister','Meio-campista',20),
  ('ARG','José Manuel López','Atacante',21),
  ('ARG','Lautaro Martínez','Atacante',22),
  ('ARG','Emiliano Martínez','Goleiro',23),
  ('ARG','Enzo Fernández','Meio-campista',24),
  ('ARG','Facundo Medina','Defensor',25),
  ('ARG','Nahuel Molina','Defensor',26),

  ('AUT','Alexander Schlager','Goleiro',1),
  ('AUT','David Affengruber','Defensor',2),
  ('AUT','Kevin Danso','Defensor',3),
  ('AUT','Xaver Schlager','Meio-campista',4),
  ('AUT','Stefan Posch','Defensor',5),
  ('AUT','Nicolas Seiwald','Meio-campista',6),
  ('AUT','Marko Arnautović','Atacante',7),
  ('AUT','David Alaba','Defensor',8),
  ('AUT','Marcel Sabitzer','Meio-campista',9),
  ('AUT','Florian Grillitsch','Meio-campista',10),
  ('AUT','Michael Gregoritsch','Atacante',11),
  ('AUT','Florian Wiegele','Goleiro',12),
  ('AUT','Patrick Pentz','Goleiro',13),
  ('AUT','Saša Kalajdžić','Atacante',14),
  ('AUT','Philipp Lienhart','Defensor',15),
  ('AUT','Phillipp Mwene','Defensor',16),
  ('AUT','Carney Chukwuemeka','Meio-campista',17),
  ('AUT','Romano Schmid','Meio-campista',18),
  ('AUT','Dejan Ljubičić','Meio-campista',19),
  ('AUT','Konrad Laimer','Meio-campista',20),
  ('AUT','Patrick Wimmer','Atacante',21),
  ('AUT','Alexander Prass','Meio-campista',22),
  ('AUT','Marco Friedl','Defensor',23),
  ('AUT','Paul Wanner','Meio-campista',24),
  ('AUT','Michael Svoboda','Defensor',25),
  ('AUT','Alessandro Schöpf','Meio-campista',26),

  ('JOR','Yazeed Abulaila','Goleiro',1),
  ('JOR','Mohammad Abu Hashish','Defensor',2),
  ('JOR','Abdallah Nasib','Defensor',3),
  ('JOR','Husam Abu Dahab','Defensor',4),
  ('JOR','Yazan Al-Arab','Defensor',5),
  ('JOR','Amer Jamous','Meio-campista',6),
  ('JOR','Mohammad Abu Zrayq','Atacante',7),
  ('JOR','Noor Al-Rawabdeh','Meio-campista',8),
  ('JOR','Ali Olwan','Atacante',9),
  ('JOR','Musa Al-Taamari','Atacante',10),
  ('JOR','Odeh Al-Fakhouri','Atacante',11),
  ('JOR','Nour Bani Attiah','Goleiro',12),
  ('JOR','Mahmoud Al-Mardi','Atacante',13),
  ('JOR','Rajaei Ayed','Meio-campista',14),
  ('JOR','Ibrahim Sadeh','Meio-campista',15),
  ('JOR','Mo Abualnadi','Defensor',16),
  ('JOR','Salim Obaid','Defensor',17),
  ('JOR','Mohammad Taha','Meio-campista',18),
  ('JOR','Saed Al-Rosan','Defensor',19),
  ('JOR','Mohannad Abu Taha','Meio-campista',20),
  ('JOR','Nizar Al-Rashdan','Meio-campista',21),
  ('JOR','Abdallah Al-Fakhouri','Goleiro',22),
  ('JOR','Ihsan Haddad','Defensor',23),
  ('JOR','Ali Azaizeh','Atacante',24),
  ('JOR','Mohammad Al-Dawoud','Meio-campista',25),
  ('JOR','Anas Badawi','Defensor',26),

  -- ============================================================
  -- GRUPO K: Colômbia, RD Congo, Portugal, Uzbequistão
  -- ============================================================
  ('COL','David Ospina','Goleiro',1),
  ('COL','Daniel Muñoz','Defensor',2),
  ('COL','Jhon Lucumí','Defensor',3),
  ('COL','Santiago Arias','Defensor',4),
  ('COL','Kevin Castaño','Meio-campista',5),
  ('COL','Richard Ríos','Meio-campista',6),
  ('COL','Luis Díaz','Atacante',7),
  ('COL','Jorge Carrascal','Meio-campista',8),
  ('COL','Jhon Córdoba','Atacante',9),
  ('COL','James Rodríguez','Meio-campista',10),
  ('COL','Jhon Arias','Meio-campista',11),
  ('COL','Camilo Vargas','Goleiro',12),
  ('COL','Yerry Mina','Defensor',13),
  ('COL','Gustavo Puerta','Defensor',14),
  ('COL','Juan Portilla','Meio-campista',15),
  ('COL','Jefferson Lerma','Meio-campista',16),
  ('COL','Johan Mojica','Defensor',17),
  ('COL','Willer Ditta','Defensor',18),
  ('COL','Cucho Hernández','Atacante',19),
  ('COL','Juan Fernando Quintero','Meio-campista',20),
  ('COL','Jaminton Campaz','Atacante',21),
  ('COL','Deiver Machado','Defensor',22),
  ('COL','Davinson Sánchez','Defensor',23),
  ('COL','Álvaro Montero','Goleiro',24),
  ('COL','Luis Suárez','Atacante',25),
  ('COL','Andrés Gómez','Atacante',26),

  ('COD','Lionel Mpasi','Goleiro',1),
  ('COD','Aaron Wan-Bissaka','Defensor',2),
  ('COD','Steve Kapuadi','Defensor',3),
  ('COD','Axel Tuanzebe','Defensor',4),
  ('COD','Dylan Batubinsika','Defensor',5),
  ('COD','Ngal''ayel Mukau','Meio-campista',6),
  ('COD','Nathanaël Mbuku','Meio-campista',7),
  ('COD','Samuel Moutoussamy','Meio-campista',8),
  ('COD','Brian Cipenga','Atacante',9),
  ('COD','Théo Bongonda','Meio-campista',10),
  ('COD','Gaël Kakuta','Atacante',11),
  ('COD','Joris Kayembe','Defensor',12),
  ('COD','Meschak Elia','Atacante',13),
  ('COD','Noah Sadiki','Meio-campista',14),
  ('COD','Aaron Tshibola','Meio-campista',15),
  ('COD','Timothy Fayulu','Goleiro',16),
  ('COD','Cédric Bakambu','Atacante',17),
  ('COD','Charles Pickel','Meio-campista',18),
  ('COD','Fiston Mayele','Atacante',19),
  ('COD','Yoane Wissa','Atacante',20),
  ('COD','Matthieu Epolo','Goleiro',21),
  ('COD','Chancel Mbemba','Defensor',22),
  ('COD','Simon Banza','Atacante',23),
  ('COD','Gédéon Kalulu','Defensor',24),
  ('COD','Edo Kayembe','Meio-campista',25),
  ('COD','Arthur Masuaku','Defensor',26),

  ('POR','Diogo Costa','Goleiro',1),
  ('POR','Nélson Semedo','Defensor',2),
  ('POR','Rúben Dias','Defensor',3),
  ('POR','Tomás Araújo','Defensor',4),
  ('POR','Diogo Dalot','Defensor',5),
  ('POR','Matheus Nunes','Meio-campista',6),
  ('POR','Cristiano Ronaldo','Atacante',7),
  ('POR','Bruno Fernandes','Meio-campista',8),
  ('POR','Gonçalo Ramos','Atacante',9),
  ('POR','Bernardo Silva','Meio-campista',10),
  ('POR','João Félix','Atacante',11),
  ('POR','José Sá','Goleiro',12),
  ('POR','Renato Veiga','Defensor',13),
  ('POR','Gonçalo Inácio','Defensor',14),
  ('POR','João Neves','Meio-campista',15),
  ('POR','Francisco Trincão','Atacante',16),
  ('POR','Rafael Leão','Atacante',17),
  ('POR','Pedro Neto','Atacante',18),
  ('POR','Gonçalo Guedes','Atacante',19),
  ('POR','João Cancelo','Defensor',20),
  ('POR','Rúben Neves','Meio-campista',21),
  ('POR','Rui Silva','Goleiro',22),
  ('POR','Vitinha','Meio-campista',23),
  ('POR','Samú Costa','Defensor',24),
  ('POR','Nuno Mendes','Defensor',25),
  ('POR','Francisco Conceição','Atacante',26),

  ('UZB','Utkir Yusupov','Goleiro',1),
  ('UZB','Abdukodir Khusanov','Defensor',2),
  ('UZB','Khojiakbar Alijonov','Defensor',3),
  ('UZB','Farrukh Sayfiev','Defensor',4),
  ('UZB','Rustam Ashurmatov','Defensor',5),
  ('UZB','Akmal Mozgovoy','Meio-campista',6),
  ('UZB','Otabek Shukurov','Meio-campista',7),
  ('UZB','Jamshid Iskanderov','Meio-campista',8),
  ('UZB','Odiljon Hamrobekov','Meio-campista',9),
  ('UZB','Ruslanbek Jiyanov','Meio-campista',10),
  ('UZB','Oston Urunov','Meio-campista',11),
  ('UZB','Abduvohid Nematov','Goleiro',12),
  ('UZB','Sherzod Nasrullaev','Defensor',13),
  ('UZB','Eldor Shomurodov','Atacante',14),
  ('UZB','Umar Eshmurodov','Defensor',15),
  ('UZB','Botirali Ergashev','Goleiro',16),
  ('UZB','Dostonbek Khamdamov','Meio-campista',17),
  ('UZB','Abdulla Abdullaev','Defensor',18),
  ('UZB','Azizjon Ganiev','Meio-campista',19),
  ('UZB','Azizbek Amonov','Atacante',20),
  ('UZB','Igor Sergeev','Atacante',21),
  ('UZB','Abbosbek Fayzullaev','Meio-campista',22),
  ('UZB','Sherzod Esanov','Meio-campista',23),
  ('UZB','Bekhruz Karimov','Defensor',24),
  ('UZB','Avazbek Ulmasaliev','Defensor',25),
  ('UZB','Jakhongir Urozov','Defensor',26),

  -- ============================================================
  -- GRUPO L: Croácia, Inglaterra, Gana, Panamá
  -- ============================================================
  ('CRO','Dominik Livaković','Goleiro',1),
  ('CRO','Josip Stanišić','Defensor',2),
  ('CRO','Marin Pongračić','Defensor',3),
  ('CRO','Joško Gvardiol','Defensor',4),
  ('CRO','Duje Ćaleta-Car','Defensor',5),
  ('CRO','Josip Šutalo','Defensor',6),
  ('CRO','Nikola Moro','Meio-campista',7),
  ('CRO','Mateo Kovačić','Meio-campista',8),
  ('CRO','Andrej Kramarić','Atacante',9),
  ('CRO','Luka Modrić','Meio-campista',10),
  ('CRO','Ante Budimir','Atacante',11),
  ('CRO','Ivor Pandur','Goleiro',12),
  ('CRO','Nikola Vlašić','Meio-campista',13),
  ('CRO','Ivan Perišić','Atacante',14),
  ('CRO','Mario Pašalić','Meio-campista',15),
  ('CRO','Martin Baturina','Meio-campista',16),
  ('CRO','Petar Sučić','Meio-campista',17),
  ('CRO','Kristijan Jakić','Defensor',18),
  ('CRO','Toni Fruk','Meio-campista',19),
  ('CRO','Igor Matanović','Atacante',20),
  ('CRO','Luka Sučić','Meio-campista',21),
  ('CRO','Luka Vušković','Defensor',22),
  ('CRO','Dominik Kotarski','Goleiro',23),
  ('CRO','Marco Pašalić','Atacante',24),
  ('CRO','Martin Erlić','Defensor',25),
  ('CRO','Petar Musa','Atacante',26),

  ('ENG','Jordan Pickford','Goleiro',1),
  ('ENG','Ezri Konsa','Defensor',2),
  ('ENG','Nico O''Reilly','Defensor',3),
  ('ENG','Declan Rice','Meio-campista',4),
  ('ENG','John Stones','Defensor',5),
  ('ENG','Marc Guéhi','Defensor',6),
  ('ENG','Bukayo Saka','Atacante',7),
  ('ENG','Elliot Anderson','Meio-campista',8),
  ('ENG','Harry Kane','Atacante',9),
  ('ENG','Jude Bellingham','Meio-campista',10),
  ('ENG','Marcus Rashford','Atacante',11),
  ('ENG','Trevoh Chalobah','Defensor',12),
  ('ENG','Dean Henderson','Goleiro',13),
  ('ENG','Jordan Henderson','Meio-campista',14),
  ('ENG','Dan Burn','Defensor',15),
  ('ENG','Kobbie Mainoo','Meio-campista',16),
  ('ENG','Morgan Rogers','Meio-campista',17),
  ('ENG','Anthony Gordon','Atacante',18),
  ('ENG','Ollie Watkins','Atacante',19),
  ('ENG','Noni Madueke','Atacante',20),
  ('ENG','Eberechi Eze','Meio-campista',21),
  ('ENG','Ivan Toney','Atacante',22),
  ('ENG','James Trafford','Goleiro',23),
  ('ENG','Reece James','Defensor',24),
  ('ENG','Djed Spence','Defensor',25),
  ('ENG','Jarell Quansah','Defensor',26),

  ('GHA','Lawrence Ati-Zigi','Goleiro',1),
  ('GHA','Alidu Seidu','Defensor',2),
  ('GHA','Caleb Yirenkyi','Meio-campista',3),
  ('GHA','Jonas Adjetey','Defensor',4),
  ('GHA','Thomas Partey','Meio-campista',5),
  ('GHA','Abdul Mumin','Defensor',6),
  ('GHA','Abdul Fatawu','Atacante',7),
  ('GHA','Kwasi Sibo','Meio-campista',8),
  ('GHA','Jordan Ayew','Atacante',9),
  ('GHA','Brandon Thomas-Asante','Atacante',10),
  ('GHA','Antoine Semenyo','Meio-campista',11),
  ('GHA','Joseph Anang','Goleiro',12),
  ('GHA','Christopher Bonsu Baah','Atacante',13),
  ('GHA','Gideon Mensah','Defensor',14),
  ('GHA','Elisha Owusu','Meio-campista',15),
  ('GHA','Benjamin Asare','Goleiro',16),
  ('GHA','Abdul Rahman Baba','Defensor',17),
  ('GHA','Jerome Opoku','Defensor',18),
  ('GHA','Iñaki Williams','Atacante',19),
  ('GHA','Augustine Boakye','Meio-campista',20),
  ('GHA','Kojo Peprah Oppong','Defensor',21),
  ('GHA','Kamaldeen Sulemana','Atacante',22),
  ('GHA','Derrick Luckassen','Defensor',23),
  ('GHA','Ernest Nuamah','Atacante',24),
  ('GHA','Prince Kwabena Adu','Atacante',25),
  ('GHA','Marvin Senaya','Defensor',26),

  ('PAN','Luis Mejía','Goleiro',1),
  ('PAN','César Blackman','Defensor',2),
  ('PAN','José Córdoba','Defensor',3),
  ('PAN','Fidel Escobar','Defensor',4),
  ('PAN','Edgardo Fariña','Defensor',5),
  ('PAN','Cristian Martínez','Meio-campista',6),
  ('PAN','José Luis Rodríguez','Meio-campista',7),
  ('PAN','Adalberto Carrasquilla','Meio-campista',8),
  ('PAN','Tomás Rodríguez','Atacante',9),
  ('PAN','Ismael Díaz','Meio-campista',10),
  ('PAN','Yoel Bárcenas','Meio-campista',11),
  ('PAN','César Samudio','Goleiro',12),
  ('PAN','Jiovany Ramos','Defensor',13),
  ('PAN','Carlos Harvey','Defensor',14),
  ('PAN','Eric Davis','Defensor',15),
  ('PAN','Andrés Andrade','Defensor',16),
  ('PAN','José Fajardo','Atacante',17),
  ('PAN','Cecilio Waterman','Atacante',18),
  ('PAN','Alberto Quintero','Meio-campista',19),
  ('PAN','Aníbal Godoy','Meio-campista',20),
  ('PAN','César Yanis','Meio-campista',21),
  ('PAN','Orlando Mosquera','Goleiro',22),
  ('PAN','Michael Amir Murillo','Defensor',23),
  ('PAN','Azarias Londoño','Atacante',24),
  ('PAN','Roderick Miller','Defensor',25),
  ('PAN','Jorge Gutiérrez','Defensor',26)

) AS v(code, name, position, shirt_number)
JOIN teams t ON t.code = v.code;

-- Confirmação
SELECT COUNT(*) AS total_jogadores FROM players;
